// Pentagon numbers

/*
Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimized; what is the value of D?
*/

function isPentagonal(number) {
  return (Math.sqrt(24 * number + 1) + 1) % 6 === 0;
}

function findValueOfD() {
  const now = Date.now();
  let minDiff = null;
  let k = 1;
  while (minDiff === null) {
    k++;
    const pentagonalNumber = k * (3 * k - 1) / 2;
    for (let j = k - 1; j > 0; j--) {
      const previousPentagonalNumber = j * (3 * j - 1) / 2;
      if (isPentagonal(pentagonalNumber + previousPentagonalNumber) && isPentagonal(pentagonalNumber - previousPentagonalNumber)) {
        minDiff = pentagonalNumber - previousPentagonalNumber;
        break;
      }
    }
  }
  console.log(require('../utils/time')(now));
  return minDiff;
}

console.log(findValueOfD()); // 34327592 - wrong
