// Triangular, pentagonal, and hexagonal

/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
*/

function isPentagonal(number) {
  return (Math.sqrt(24 * number + 1) + 1) % 6 === 0;
}

function isHexagonal(number) {
  return (Math.sqrt(8 * number + 1) + 1) % 4 === 0;
}

function findTrianglePentagonalHexagonalNumber(start) {
  const now = Date.now();
  let result = null;
  let n = start;
  while (result === null) {
    n++;
    const triangleNumber = n * (n + 1) / 2;
    if (isPentagonal(triangleNumber) && isHexagonal(triangleNumber)) {
      result = triangleNumber;
    }
  }
  console.log(require('../utils/time')(now));
  return result;
}

console.log(findTrianglePentagonalHexagonalNumber(285)); // 1533776805
